<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sho.Core\Sho.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sho.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="NPOI" Version="2.5.6" />
    <PackageReference Include="PdfPig" Version="0.1.10" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.0" />
    <PackageReference Include="UTF.Unknown" Version="2.5.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
